name: FastAPI CICD App

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 시크릿 존재 여부 빠르게 점검
      - name: Validate Docker secrets
        run: |
          [ -n "${{ secrets.DOCKERHUB_USERNAME }}" ] || { echo "❌ DOCKERHUB_USERNAME is missing"; exit 1; }
          [ -n "${{ secrets.DOCKERHUB_TOKEN }}" ] || { echo "❌ DOCKERHUB_TOKEN is missing"; exit 1; }

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGENAME }}:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGENAME }}:latest

      - name: Verify image tag exists on Docker Hub
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGENAME }}:${{ github.sha }}
          echo "Checking $IMAGE"
          docker buildx imagetools inspect "$IMAGE" >/dev/null
          echo "✅ Image tag exists: $IMAGE"
      
      - name: Inspect manifest (should list amd64 and/or arm64)
        run: |
          docker buildx imagetools inspect ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGENAME }}:${{ github.sha }}


      - name: Generate Dockerrun.aws.json
        run: |
          cat > Dockerrun.aws.json << 'EOF'
          {
            "AWSEBDockerrunVersion": "1",
            "Image": {
              "Name": "${DOCKER_IMAGE}",
              "Update": "true"
            },
            "Ports": [
              { "ContainerPort": "8000" }
            ],
            "Environment": [
              { "Name": "APP_MODULE", "Value": "app:app" },
              { "Name": "PORT", "Value": "8000" },
              { "Name": "HOST", "Value": "0.0.0.0" },
              { "Name": "WORKERS", "Value": "2" }
            ]
          }
          EOF
        env:
          DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGENAME }}:${{ github.sha }}


      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.AWS_EB_APPLICATION_NAME }}
          environment_name: ${{ secrets.AWS_EB_ENVIRONMENT_NAME }}
          region: ap-northeast-2
          # 매 실행마다 고유해지는 라벨 (commit+run)
          version_label: "app-${{ github.sha }}-${{ github.run_id }}"
          # 같은 라벨이 이미 있으면 그 버전을 재사용
          use_existing_version_if_available: true
          deployment_package: Dockerrun.aws.json

